// GENERATED CODE, do not edit this file.

import 'package:coap/coap.dart';

/// Configuration loading class. The config file itself is a YAML
/// file. The configuration items below are marked as optional to allow
/// the config file to contain only those entries that override the defaults.
/// The file can't be empty, so version must as a minimum be present.
class CoapConfigLogging extends DefaultCoapConfig {
  CoapConfigLogging() {
    DefaultCoapConfig.inst = this;
  }

  @override
  CoapISpec spec;

  @override
  String get logTarget => 'console';

  @override
  bool get logWarn => true;

  @override
  String get version => 'RFC7252';

  @override
  String get deduplicator => 'MarkAndSweep';

  @override
  bool get logInfo => true;

  @override
  bool get logError => true;

  @override
  bool get logDebug => true;
}
