// GENERATED CODE, do not edit this file.

import 'package:coap/coap.dart';

/// Configuration loading class. The config file itself is a YAML
/// file. The configuration items below are marked as optional to allow
/// the config file to contain only those entries that override the defaults.
/// The file can't be empty, so version must as a minimum be present.
class CoapConfigAll extends DefaultCoapConfig {
  @override
  String get version => 'RFC7252';

  @override
  int get defaultPort => 1;

  @override
  int get defaultSecurePort => 2;

  @override
  int get httpPort => 3;

  @override
  int get defaultTimeout => 4;

  @override
  int get ackTimeout => 5;

  @override
  double get ackRandomFactor => 6.0;

  @override
  double get ackTimeoutScale => 7.0;

  @override
  int get maxRetransmit => 8;

  @override
  int get maxMessageSize => 9;

  @override
  int get defaultBlockSize => 10;

  @override
  int get blockwiseStatusLifetime => 11;

  @override
  bool get useRandomIDStart => false;

  @override
  int get notificationMaxAge => 12;

  @override
  int get notificationCheckIntervalTime => 13;

  @override
  int get notificationCheckIntervalCount => 14;

  @override
  int get notificationReregistrationBackoff => 15;

  @override
  int get cropRotationPeriod => 16;

  @override
  int get exchangeLifetime => 17;

  @override
  int get markAndSweepInterval => 18;

  @override
  int get channelReceivePacketSize => 19;

  @override
  String get deduplicator => 'MarkAndSweep';
}
